name: pp_438
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.2.0+5

environment:
  sdk: ^3.4.3

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.1.0
  connectivity_plus: ^6.1.4
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  equatable: ^2.0.5
  intl: ^0.19.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.3.7
  smooth_page_indicator: ^1.1.0
  get_it: ^7.6.7
  carousel_slider_plus: ^7.1.0
  firebase_core: ^3.13.0
  firebase_crashlytics: ^4.3.5
  firebase_remote_config: ^5.4.3
  webview_flutter_android: ^4.4.1
  webview_flutter_wkwebview: 3.16.3
  webview_flutter: ^4.4.4
  uuid: ^4.4.0
  hive: ^2.2.3
  hive_flutter: ^1.0.0
  package_info_plus: ^8.3.0
  device_info_plus: ^11.4.0
  flutter_markdown: ^0.7.2+1
  url_launcher: ^6.3.0
  email_validator: ^3.0.0
  in_app_review: ^2.0.9
  calendar_date_picker2: ^2.0.0
  ff_bloc: ^1.0.3
  path: ^1.8.0
  yaml: ^3.1.0
  yaml_edit: ^2.0.3
  numberpicker: ^2.1.2
  wheel_chooser: ^1.1.2
  google_fonts: ^6.2.1
  flutter_switch: ^0.3.2
  toggle_switch: ^2.3.0
  animated_segmented_tab_control: ^2.0.0
  image_picker: ^1.1.2
  flutter_pannable_rating_bar: ^2.7.2+1
  auto_route: 7.8.4
  flutter_rating_bar: ^4.0.1
  dropdown_button2: ^2.3.9
  flutter_custom_tab_bar: ^1.2.1
  flutter_timer_countdown: ^1.0.7
  custom_timer: ^0.2.3
  path_provider: ^2.1.3
  flagsmith: ^6.0.1

dev_dependencies:
  auto_route_generator: 7.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.1.7 
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/main_icon2.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true

flutter_native_splash:

  color: "#1C1C1C"

  image: assets/images/icon.png

  android_12:
